grpc:
  listen: "tcp://0.0.0.0:9001"
  proto: "./protos/market.proto"
  workers:
    command: "php artisan market:data"
    pool:
      numWorkers: 4

metrics:
  address: localhost:2112

limit:
  interval: 1
  services:
    grpc:
      maxMemory: 100
      TTL: 0
      idleTTL: 0
      execTTL: 60
