<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market\KChartResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.KChartResponse.Data</code>
 */
class Data extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.market.KChart kcharts = 1;</code>
     */
    private $kcharts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Market\KChart[]|\Google\Protobuf\Internal\RepeatedField $kcharts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.market.KChart kcharts = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKcharts()
    {
        return $this->kcharts;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.market.KChart kcharts = 1;</code>
     * @param \Proto\Market\KChart[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKcharts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Market\KChart::class);
        $this->kcharts = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Data::class, \Proto\Market\KChartResponse_Data::class);

