<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Spiral\GRPC;

interface ChartInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "proto.market.Chart";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param TickRequest $in
    * @return TickResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function fetchTicks(GRPC\ContextInterface $ctx, TickRequest $in): TickResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param KChartRequest $in
    * @return KChartResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function fetchKCharts(GRPC\ContextInterface $ctx, KChartRequest $in): KChartResponse;
}
