<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.Criteria</code>
 */
class Criteria extends \Google\Protobuf\Internal\Message
{
    /**
     * 搜索字符串（暂只支持股票代码）
     *
     * Generated from protobuf field <code>string keywords = 1;</code>
     */
    protected $keywords = '';
    /**
     * string prdt_type = 2;
     * string exchange_code = 3;
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     */
    protected $page = 0;
    /**
     * 每页数量，默认20
     *
     * Generated from protobuf field <code>int32 size = 3;</code>
     */
    protected $size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $keywords
     *           搜索字符串（暂只支持股票代码）
     *     @type int $page
     *           string prdt_type = 2;
     *           string exchange_code = 3;
     *     @type int $size
     *           每页数量，默认20
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * 搜索字符串（暂只支持股票代码）
     *
     * Generated from protobuf field <code>string keywords = 1;</code>
     * @return string
     */
    public function getKeywords()
    {
        return $this->keywords;
    }

    /**
     * 搜索字符串（暂只支持股票代码）
     *
     * Generated from protobuf field <code>string keywords = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeywords($var)
    {
        GPBUtil::checkString($var, True);
        $this->keywords = $var;

        return $this;
    }

    /**
     * string prdt_type = 2;
     * string exchange_code = 3;
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * string prdt_type = 2;
     * string exchange_code = 3;
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * 每页数量，默认20
     *
     * Generated from protobuf field <code>int32 size = 3;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * 每页数量，默认20
     *
     * Generated from protobuf field <code>int32 size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;

        return $this;
    }

}

