<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.Criteria</code>
 */
class Criteria extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string keywords = 1;</code>
     */
    protected $keywords = '';
    /**
     * Generated from protobuf field <code>string prdt_type = 2;</code>
     */
    protected $prdt_type = '';
    /**
     * Generated from protobuf field <code>string exchange_code = 3;</code>
     */
    protected $exchange_code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $keywords
     *     @type string $prdt_type
     *     @type string $exchange_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string keywords = 1;</code>
     * @return string
     */
    public function getKeywords()
    {
        return $this->keywords;
    }

    /**
     * Generated from protobuf field <code>string keywords = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeywords($var)
    {
        GPBUtil::checkString($var, True);
        $this->keywords = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prdt_type = 2;</code>
     * @return string
     */
    public function getPrdtType()
    {
        return $this->prdt_type;
    }

    /**
     * Generated from protobuf field <code>string prdt_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPrdtType($var)
    {
        GPBUtil::checkString($var, True);
        $this->prdt_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string exchange_code = 3;</code>
     * @return string
     */
    public function getExchangeCode()
    {
        return $this->exchange_code;
    }

    /**
     * Generated from protobuf field <code>string exchange_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setExchangeCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->exchange_code = $var;

        return $this;
    }

}

