<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.KChart</code>
 */
class KChart extends \Google\Protobuf\Internal\Message
{
    /**
     * 开盘价
     *
     * Generated from protobuf field <code>string open = 1;</code>
     */
    protected $open = '';
    /**
     * 收盘价
     *
     * Generated from protobuf field <code>string close = 2;</code>
     */
    protected $close = '';
    /**
     * 最高价
     *
     * Generated from protobuf field <code>string high = 3;</code>
     */
    protected $high = '';
    /**
     * 最低价
     *
     * Generated from protobuf field <code>string low = 4;</code>
     */
    protected $low = '';
    /**
     * 涨跌额
     *
     * Generated from protobuf field <code>string chg_sum = 5;</code>
     */
    protected $chg_sum = '';
    /**
     * 涨跌幅
     *
     * Generated from protobuf field <code>string chg_ratio = 6;</code>
     */
    protected $chg_ratio = '';
    /**
     * 成交量（股数）
     *
     * Generated from protobuf field <code>string volume = 7;</code>
     */
    protected $volume = '';
    /**
     * 成交额
     *
     * Generated from protobuf field <code>string turnover = 8;</code>
     */
    protected $turnover = '';
    /**
     * 日期，格式yyyy/mm/dd
     *
     * Generated from protobuf field <code>string date = 9;</code>
     */
    protected $date = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $open
     *           开盘价
     *     @type string $close
     *           收盘价
     *     @type string $high
     *           最高价
     *     @type string $low
     *           最低价
     *     @type string $chg_sum
     *           涨跌额
     *     @type string $chg_ratio
     *           涨跌幅
     *     @type string $volume
     *           成交量（股数）
     *     @type string $turnover
     *           成交额
     *     @type string $date
     *           日期，格式yyyy/mm/dd
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * 开盘价
     *
     * Generated from protobuf field <code>string open = 1;</code>
     * @return string
     */
    public function getOpen()
    {
        return $this->open;
    }

    /**
     * 开盘价
     *
     * Generated from protobuf field <code>string open = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOpen($var)
    {
        GPBUtil::checkString($var, True);
        $this->open = $var;

        return $this;
    }

    /**
     * 收盘价
     *
     * Generated from protobuf field <code>string close = 2;</code>
     * @return string
     */
    public function getClose()
    {
        return $this->close;
    }

    /**
     * 收盘价
     *
     * Generated from protobuf field <code>string close = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClose($var)
    {
        GPBUtil::checkString($var, True);
        $this->close = $var;

        return $this;
    }

    /**
     * 最高价
     *
     * Generated from protobuf field <code>string high = 3;</code>
     * @return string
     */
    public function getHigh()
    {
        return $this->high;
    }

    /**
     * 最高价
     *
     * Generated from protobuf field <code>string high = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHigh($var)
    {
        GPBUtil::checkString($var, True);
        $this->high = $var;

        return $this;
    }

    /**
     * 最低价
     *
     * Generated from protobuf field <code>string low = 4;</code>
     * @return string
     */
    public function getLow()
    {
        return $this->low;
    }

    /**
     * 最低价
     *
     * Generated from protobuf field <code>string low = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLow($var)
    {
        GPBUtil::checkString($var, True);
        $this->low = $var;

        return $this;
    }

    /**
     * 涨跌额
     *
     * Generated from protobuf field <code>string chg_sum = 5;</code>
     * @return string
     */
    public function getChgSum()
    {
        return $this->chg_sum;
    }

    /**
     * 涨跌额
     *
     * Generated from protobuf field <code>string chg_sum = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setChgSum($var)
    {
        GPBUtil::checkString($var, True);
        $this->chg_sum = $var;

        return $this;
    }

    /**
     * 涨跌幅
     *
     * Generated from protobuf field <code>string chg_ratio = 6;</code>
     * @return string
     */
    public function getChgRatio()
    {
        return $this->chg_ratio;
    }

    /**
     * 涨跌幅
     *
     * Generated from protobuf field <code>string chg_ratio = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setChgRatio($var)
    {
        GPBUtil::checkString($var, True);
        $this->chg_ratio = $var;

        return $this;
    }

    /**
     * 成交量（股数）
     *
     * Generated from protobuf field <code>string volume = 7;</code>
     * @return string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * 成交量（股数）
     *
     * Generated from protobuf field <code>string volume = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkString($var, True);
        $this->volume = $var;

        return $this;
    }

    /**
     * 成交额
     *
     * Generated from protobuf field <code>string turnover = 8;</code>
     * @return string
     */
    public function getTurnover()
    {
        return $this->turnover;
    }

    /**
     * 成交额
     *
     * Generated from protobuf field <code>string turnover = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTurnover($var)
    {
        GPBUtil::checkString($var, True);
        $this->turnover = $var;

        return $this;
    }

    /**
     * 日期，格式yyyy/mm/dd
     *
     * Generated from protobuf field <code>string date = 9;</code>
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * 日期，格式yyyy/mm/dd
     *
     * Generated from protobuf field <code>string date = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;

        return $this;
    }

}

