<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

if (false) {
    /**
     * This class is deprecated. Use Proto\Market\KChartResponse\Data instead.
     * @deprecated
     */
    class KChartResponse_Data {}
}
class_exists(KChartResponse\Data::class);
@trigger_error('Proto\Market\KChartResponse_Data is deprecated and will be removed in the next major release. Use Proto\Market\KChartResponse\Data instead', E_USER_DEPRECATED);

