<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.KChartRequest</code>
 */
class KChartRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.market.Stock stock = 1;</code>
     */
    protected $stock = null;
    /**
     * 从1开始
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     */
    protected $page = 0;
    /**
     * 每页数量，默认20
     *
     * Generated from protobuf field <code>int32 size = 3;</code>
     */
    protected $size = 0;
    /**
     * 偏移量 (>=0)
     *
     * Generated from protobuf field <code>int32 offset = 4;</code>
     */
    protected $offset = 0;
    /**
     * 每次取数量 (1 <= n <= 250)
     *
     * Generated from protobuf field <code>int32 limit = 5;</code>
     */
    protected $limit = 0;
    /**
     * 按时间排序，desc-倒序，asc-正序，默认desc
     *
     * Generated from protobuf field <code>string order = 6;</code>
     */
    protected $order = '';
    /**
     * K线图类型，默认day
     *
     * Generated from protobuf field <code>string type = 7;</code>
     */
    protected $type = '';
    /**
     * 起始日期，格式：yyyy-mm-dd
     *
     * Generated from protobuf field <code>string start_date = 8;</code>
     */
    protected $start_date = '';
    /**
     * 结束日期，格式：yyyy-mm-dd
     *
     * Generated from protobuf field <code>string end_date = 9;</code>
     */
    protected $end_date = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Market\Stock $stock
     *     @type int $page
     *           从1开始
     *     @type int $size
     *           每页数量，默认20
     *     @type int $offset
     *           偏移量 (>=0)
     *     @type int $limit
     *           每次取数量 (1 <= n <= 250)
     *     @type string $order
     *           按时间排序，desc-倒序，asc-正序，默认desc
     *     @type string $type
     *           K线图类型，默认day
     *     @type string $start_date
     *           起始日期，格式：yyyy-mm-dd
     *     @type string $end_date
     *           结束日期，格式：yyyy-mm-dd
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.market.Stock stock = 1;</code>
     * @return \Proto\Market\Stock
     */
    public function getStock()
    {
        return $this->stock;
    }

    /**
     * Generated from protobuf field <code>.proto.market.Stock stock = 1;</code>
     * @param \Proto\Market\Stock $var
     * @return $this
     */
    public function setStock($var)
    {
        GPBUtil::checkMessage($var, \Proto\Market\Stock::class);
        $this->stock = $var;

        return $this;
    }

    /**
     * 从1开始
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * 从1开始
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * 每页数量，默认20
     *
     * Generated from protobuf field <code>int32 size = 3;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * 每页数量，默认20
     *
     * Generated from protobuf field <code>int32 size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;

        return $this;
    }

    /**
     * 偏移量 (>=0)
     *
     * Generated from protobuf field <code>int32 offset = 4;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * 偏移量 (>=0)
     *
     * Generated from protobuf field <code>int32 offset = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;

        return $this;
    }

    /**
     * 每次取数量 (1 <= n <= 250)
     *
     * Generated from protobuf field <code>int32 limit = 5;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * 每次取数量 (1 <= n <= 250)
     *
     * Generated from protobuf field <code>int32 limit = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * 按时间排序，desc-倒序，asc-正序，默认desc
     *
     * Generated from protobuf field <code>string order = 6;</code>
     * @return string
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * 按时间排序，desc-倒序，asc-正序，默认desc
     *
     * Generated from protobuf field <code>string order = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkString($var, True);
        $this->order = $var;

        return $this;
    }

    /**
     * K线图类型，默认day
     *
     * Generated from protobuf field <code>string type = 7;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * K线图类型，默认day
     *
     * Generated from protobuf field <code>string type = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * 起始日期，格式：yyyy-mm-dd
     *
     * Generated from protobuf field <code>string start_date = 8;</code>
     * @return string
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * 起始日期，格式：yyyy-mm-dd
     *
     * Generated from protobuf field <code>string start_date = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_date = $var;

        return $this;
    }

    /**
     * 结束日期，格式：yyyy-mm-dd
     *
     * Generated from protobuf field <code>string end_date = 9;</code>
     * @return string
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    /**
     * 结束日期，格式：yyyy-mm-dd
     *
     * Generated from protobuf field <code>string end_date = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_date = $var;

        return $this;
    }

}

