<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.Quotation</code>
 */
class Quotation extends \Google\Protobuf\Internal\Message
{
    /**
     * 当前价格
     *
     * Generated from protobuf field <code>string price = 1;</code>
     */
    protected $price = '';
    /**
     * 当日开市价
     *
     * Generated from protobuf field <code>string open = 2;</code>
     */
    protected $open = '';
    /**
     * 当日收市价
     *
     * Generated from protobuf field <code>string close = 3;</code>
     */
    protected $close = '';
    /**
     * 当日均价
     *
     * Generated from protobuf field <code>string average = 4;</code>
     */
    protected $average = '';
    /**
     * 当日最高价
     *
     * Generated from protobuf field <code>string day_high = 5;</code>
     */
    protected $day_high = '';
    /**
     * 当日最低价
     *
     * Generated from protobuf field <code>string day_low = 6;</code>
     */
    protected $day_low = '';
    /**
     * 上一交易日收市价
     *
     * Generated from protobuf field <code>string last_close = 7;</code>
     */
    protected $last_close = '';
    /**
     * 当日涨跌额
     *
     * Generated from protobuf field <code>string chg_sum = 8;</code>
     */
    protected $chg_sum = '';
    /**
     * 当日涨跌幅(%)
     *
     * Generated from protobuf field <code>string chg_ratio = 9;</code>
     */
    protected $chg_ratio = '';
    /**
     * 最后成交时间（时间戳）
     *
     * Generated from protobuf field <code>string last_trade_ts = 10;</code>
     */
    protected $last_trade_ts = '';
    /**
     * 交易状态（待定）
     *
     * Generated from protobuf field <code>string trade_status = 11;</code>
     */
    protected $trade_status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $price
     *           当前价格
     *     @type string $open
     *           当日开市价
     *     @type string $close
     *           当日收市价
     *     @type string $average
     *           当日均价
     *     @type string $day_high
     *           当日最高价
     *     @type string $day_low
     *           当日最低价
     *     @type string $last_close
     *           上一交易日收市价
     *     @type string $chg_sum
     *           当日涨跌额
     *     @type string $chg_ratio
     *           当日涨跌幅(%)
     *     @type string $last_trade_ts
     *           最后成交时间（时间戳）
     *     @type string $trade_status
     *           交易状态（待定）
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * 当前价格
     *
     * Generated from protobuf field <code>string price = 1;</code>
     * @return string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * 当前价格
     *
     * Generated from protobuf field <code>string price = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->price = $var;

        return $this;
    }

    /**
     * 当日开市价
     *
     * Generated from protobuf field <code>string open = 2;</code>
     * @return string
     */
    public function getOpen()
    {
        return $this->open;
    }

    /**
     * 当日开市价
     *
     * Generated from protobuf field <code>string open = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOpen($var)
    {
        GPBUtil::checkString($var, True);
        $this->open = $var;

        return $this;
    }

    /**
     * 当日收市价
     *
     * Generated from protobuf field <code>string close = 3;</code>
     * @return string
     */
    public function getClose()
    {
        return $this->close;
    }

    /**
     * 当日收市价
     *
     * Generated from protobuf field <code>string close = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClose($var)
    {
        GPBUtil::checkString($var, True);
        $this->close = $var;

        return $this;
    }

    /**
     * 当日均价
     *
     * Generated from protobuf field <code>string average = 4;</code>
     * @return string
     */
    public function getAverage()
    {
        return $this->average;
    }

    /**
     * 当日均价
     *
     * Generated from protobuf field <code>string average = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAverage($var)
    {
        GPBUtil::checkString($var, True);
        $this->average = $var;

        return $this;
    }

    /**
     * 当日最高价
     *
     * Generated from protobuf field <code>string day_high = 5;</code>
     * @return string
     */
    public function getDayHigh()
    {
        return $this->day_high;
    }

    /**
     * 当日最高价
     *
     * Generated from protobuf field <code>string day_high = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDayHigh($var)
    {
        GPBUtil::checkString($var, True);
        $this->day_high = $var;

        return $this;
    }

    /**
     * 当日最低价
     *
     * Generated from protobuf field <code>string day_low = 6;</code>
     * @return string
     */
    public function getDayLow()
    {
        return $this->day_low;
    }

    /**
     * 当日最低价
     *
     * Generated from protobuf field <code>string day_low = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDayLow($var)
    {
        GPBUtil::checkString($var, True);
        $this->day_low = $var;

        return $this;
    }

    /**
     * 上一交易日收市价
     *
     * Generated from protobuf field <code>string last_close = 7;</code>
     * @return string
     */
    public function getLastClose()
    {
        return $this->last_close;
    }

    /**
     * 上一交易日收市价
     *
     * Generated from protobuf field <code>string last_close = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setLastClose($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_close = $var;

        return $this;
    }

    /**
     * 当日涨跌额
     *
     * Generated from protobuf field <code>string chg_sum = 8;</code>
     * @return string
     */
    public function getChgSum()
    {
        return $this->chg_sum;
    }

    /**
     * 当日涨跌额
     *
     * Generated from protobuf field <code>string chg_sum = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setChgSum($var)
    {
        GPBUtil::checkString($var, True);
        $this->chg_sum = $var;

        return $this;
    }

    /**
     * 当日涨跌幅(%)
     *
     * Generated from protobuf field <code>string chg_ratio = 9;</code>
     * @return string
     */
    public function getChgRatio()
    {
        return $this->chg_ratio;
    }

    /**
     * 当日涨跌幅(%)
     *
     * Generated from protobuf field <code>string chg_ratio = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setChgRatio($var)
    {
        GPBUtil::checkString($var, True);
        $this->chg_ratio = $var;

        return $this;
    }

    /**
     * 最后成交时间（时间戳）
     *
     * Generated from protobuf field <code>string last_trade_ts = 10;</code>
     * @return string
     */
    public function getLastTradeTs()
    {
        return $this->last_trade_ts;
    }

    /**
     * 最后成交时间（时间戳）
     *
     * Generated from protobuf field <code>string last_trade_ts = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setLastTradeTs($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_trade_ts = $var;

        return $this;
    }

    /**
     * 交易状态（待定）
     *
     * Generated from protobuf field <code>string trade_status = 11;</code>
     * @return string
     */
    public function getTradeStatus()
    {
        return $this->trade_status;
    }

    /**
     * 交易状态（待定）
     *
     * Generated from protobuf field <code>string trade_status = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setTradeStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->trade_status = $var;

        return $this;
    }

}

