<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.StockInfo</code>
 */
class StockInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string exchange_code = 1;</code>
     */
    protected $exchange_code = '';
    /**
     * Generated from protobuf field <code>string market_code = 2;</code>
     */
    protected $market_code = '';
    /**
     * Generated from protobuf field <code>string prdt_type = 3;</code>
     */
    protected $prdt_type = '';
    /**
     * Generated from protobuf field <code>string stock_code = 4;</code>
     */
    protected $stock_code = '';
    /**
     * Generated from protobuf field <code>string stock_name = 5;</code>
     */
    protected $stock_name = '';
    /**
     * Generated from protobuf field <code>string ISIN = 6;</code>
     */
    protected $ISIN = '';
    /**
     * Generated from protobuf field <code>string currency = 7;</code>
     */
    protected $currency = '';
    /**
     * Generated from protobuf field <code>int32 board_lot = 8;</code>
     */
    protected $board_lot = 0;
    /**
     * Generated from protobuf field <code>int32 status = 9;</code>
     */
    protected $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $exchange_code
     *     @type string $market_code
     *     @type string $prdt_type
     *     @type string $stock_code
     *     @type string $stock_name
     *     @type string $ISIN
     *     @type string $currency
     *     @type int $board_lot
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string exchange_code = 1;</code>
     * @return string
     */
    public function getExchangeCode()
    {
        return $this->exchange_code;
    }

    /**
     * Generated from protobuf field <code>string exchange_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setExchangeCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->exchange_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string market_code = 2;</code>
     * @return string
     */
    public function getMarketCode()
    {
        return $this->market_code;
    }

    /**
     * Generated from protobuf field <code>string market_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMarketCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->market_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prdt_type = 3;</code>
     * @return string
     */
    public function getPrdtType()
    {
        return $this->prdt_type;
    }

    /**
     * Generated from protobuf field <code>string prdt_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrdtType($var)
    {
        GPBUtil::checkString($var, True);
        $this->prdt_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stock_code = 4;</code>
     * @return string
     */
    public function getStockCode()
    {
        return $this->stock_code;
    }

    /**
     * Generated from protobuf field <code>string stock_code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStockCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->stock_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stock_name = 5;</code>
     * @return string
     */
    public function getStockName()
    {
        return $this->stock_name;
    }

    /**
     * Generated from protobuf field <code>string stock_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStockName($var)
    {
        GPBUtil::checkString($var, True);
        $this->stock_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ISIN = 6;</code>
     * @return string
     */
    public function getISIN()
    {
        return $this->ISIN;
    }

    /**
     * Generated from protobuf field <code>string ISIN = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setISIN($var)
    {
        GPBUtil::checkString($var, True);
        $this->ISIN = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string currency = 7;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 board_lot = 8;</code>
     * @return int
     */
    public function getBoardLot()
    {
        return $this->board_lot;
    }

    /**
     * Generated from protobuf field <code>int32 board_lot = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setBoardLot($var)
    {
        GPBUtil::checkInt32($var);
        $this->board_lot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 9;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

}

