<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.Stocks</code>
 */
class Stocks extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.market.Stock stocks = 1;</code>
     */
    private $stocks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Market\Stock[]|\Google\Protobuf\Internal\RepeatedField $stocks
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.market.Stock stocks = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStocks()
    {
        return $this->stocks;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.market.Stock stocks = 1;</code>
     * @param \Proto\Market\Stock[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Market\Stock::class);
        $this->stocks = $arr;

        return $this;
    }

}

