<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.Tick</code>
 */
class Tick extends \Google\Protobuf\Internal\Message
{
    /**
     * 价格
     *
     * Generated from protobuf field <code>string price = 1;</code>
     */
    protected $price = '';
    /**
     * 均价
     *
     * Generated from protobuf field <code>string average = 2;</code>
     */
    protected $average = '';
    /**
     * 涨跌额
     *
     * Generated from protobuf field <code>string chg_ratio = 3;</code>
     */
    protected $chg_ratio = '';
    /**
     * 涨跌幅
     *
     * Generated from protobuf field <code>string chg_sum = 4;</code>
     */
    protected $chg_sum = '';
    /**
     * 成交量（股数）
     *
     * Generated from protobuf field <code>string volume = 5;</code>
     */
    protected $volume = '';
    /**
     * 成交额
     *
     * Generated from protobuf field <code>string turnover = 6;</code>
     */
    protected $turnover = '';
    /**
     * 时间点，格式 2020/04/23 17:28
     *
     * Generated from protobuf field <code>string time = 7;</code>
     */
    protected $time = '';
    /**
     * 时间戳
     *
     * Generated from protobuf field <code>int32 timestamp = 8;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $price
     *           价格
     *     @type string $average
     *           均价
     *     @type string $chg_ratio
     *           涨跌额
     *     @type string $chg_sum
     *           涨跌幅
     *     @type string $volume
     *           成交量（股数）
     *     @type string $turnover
     *           成交额
     *     @type string $time
     *           时间点，格式 2020/04/23 17:28
     *     @type int $timestamp
     *           时间戳
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * 价格
     *
     * Generated from protobuf field <code>string price = 1;</code>
     * @return string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * 价格
     *
     * Generated from protobuf field <code>string price = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->price = $var;

        return $this;
    }

    /**
     * 均价
     *
     * Generated from protobuf field <code>string average = 2;</code>
     * @return string
     */
    public function getAverage()
    {
        return $this->average;
    }

    /**
     * 均价
     *
     * Generated from protobuf field <code>string average = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAverage($var)
    {
        GPBUtil::checkString($var, True);
        $this->average = $var;

        return $this;
    }

    /**
     * 涨跌额
     *
     * Generated from protobuf field <code>string chg_ratio = 3;</code>
     * @return string
     */
    public function getChgRatio()
    {
        return $this->chg_ratio;
    }

    /**
     * 涨跌额
     *
     * Generated from protobuf field <code>string chg_ratio = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setChgRatio($var)
    {
        GPBUtil::checkString($var, True);
        $this->chg_ratio = $var;

        return $this;
    }

    /**
     * 涨跌幅
     *
     * Generated from protobuf field <code>string chg_sum = 4;</code>
     * @return string
     */
    public function getChgSum()
    {
        return $this->chg_sum;
    }

    /**
     * 涨跌幅
     *
     * Generated from protobuf field <code>string chg_sum = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setChgSum($var)
    {
        GPBUtil::checkString($var, True);
        $this->chg_sum = $var;

        return $this;
    }

    /**
     * 成交量（股数）
     *
     * Generated from protobuf field <code>string volume = 5;</code>
     * @return string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * 成交量（股数）
     *
     * Generated from protobuf field <code>string volume = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkString($var, True);
        $this->volume = $var;

        return $this;
    }

    /**
     * 成交额
     *
     * Generated from protobuf field <code>string turnover = 6;</code>
     * @return string
     */
    public function getTurnover()
    {
        return $this->turnover;
    }

    /**
     * 成交额
     *
     * Generated from protobuf field <code>string turnover = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTurnover($var)
    {
        GPBUtil::checkString($var, True);
        $this->turnover = $var;

        return $this;
    }

    /**
     * 时间点，格式 2020/04/23 17:28
     *
     * Generated from protobuf field <code>string time = 7;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * 时间点，格式 2020/04/23 17:28
     *
     * Generated from protobuf field <code>string time = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->time = $var;

        return $this;
    }

    /**
     * 时间戳
     *
     * Generated from protobuf field <code>int32 timestamp = 8;</code>
     * @return int
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * 时间戳
     *
     * Generated from protobuf field <code>int32 timestamp = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt32($var);
        $this->timestamp = $var;

        return $this;
    }

}

