<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.Tick</code>
 */
class Tick extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string price = 1;</code>
     */
    protected $price = '';
    /**
     * Generated from protobuf field <code>string average = 2;</code>
     */
    protected $average = '';
    /**
     * Generated from protobuf field <code>string chg_ratio = 3;</code>
     */
    protected $chg_ratio = '';
    /**
     * Generated from protobuf field <code>string chg_sum = 4;</code>
     */
    protected $chg_sum = '';
    /**
     * Generated from protobuf field <code>string volume = 5;</code>
     */
    protected $volume = '';
    /**
     * Generated from protobuf field <code>string turnover = 6;</code>
     */
    protected $turnover = '';
    /**
     * Generated from protobuf field <code>string time = 7;</code>
     */
    protected $time = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $price
     *     @type string $average
     *     @type string $chg_ratio
     *     @type string $chg_sum
     *     @type string $volume
     *     @type string $turnover
     *     @type string $time
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string price = 1;</code>
     * @return string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>string price = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string average = 2;</code>
     * @return string
     */
    public function getAverage()
    {
        return $this->average;
    }

    /**
     * Generated from protobuf field <code>string average = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAverage($var)
    {
        GPBUtil::checkString($var, True);
        $this->average = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string chg_ratio = 3;</code>
     * @return string
     */
    public function getChgRatio()
    {
        return $this->chg_ratio;
    }

    /**
     * Generated from protobuf field <code>string chg_ratio = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setChgRatio($var)
    {
        GPBUtil::checkString($var, True);
        $this->chg_ratio = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string chg_sum = 4;</code>
     * @return string
     */
    public function getChgSum()
    {
        return $this->chg_sum;
    }

    /**
     * Generated from protobuf field <code>string chg_sum = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setChgSum($var)
    {
        GPBUtil::checkString($var, True);
        $this->chg_sum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string volume = 5;</code>
     * @return string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Generated from protobuf field <code>string volume = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkString($var, True);
        $this->volume = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string turnover = 6;</code>
     * @return string
     */
    public function getTurnover()
    {
        return $this->turnover;
    }

    /**
     * Generated from protobuf field <code>string turnover = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTurnover($var)
    {
        GPBUtil::checkString($var, True);
        $this->turnover = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time = 7;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>string time = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->time = $var;

        return $this;
    }

}

