<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

if (false) {
    /**
     * This class is deprecated. Use Proto\Market\TickResponse\Data instead.
     * @deprecated
     */
    class TickResponse_Data {}
}
class_exists(TickResponse\Data::class);
@trigger_error('Proto\Market\TickResponse_Data is deprecated and will be removed in the next major release. Use Proto\Market\TickResponse\Data instead', E_USER_DEPRECATED);

