<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.TickResponse</code>
 */
class TickResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.market.Status status = 1;</code>
     */
    protected $status = null;
    /**
     * Generated from protobuf field <code>.proto.market.TickResponse.Data data = 2;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Market\Status $status
     *     @type \Proto\Market\TickResponse\Data $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.market.Status status = 1;</code>
     * @return \Proto\Market\Status
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.proto.market.Status status = 1;</code>
     * @param \Proto\Market\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Proto\Market\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.market.TickResponse.Data data = 2;</code>
     * @return \Proto\Market\TickResponse\Data
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>.proto.market.TickResponse.Data data = 2;</code>
     * @param \Proto\Market\TickResponse\Data $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Proto\Market\TickResponse_Data::class);
        $this->data = $var;

        return $this;
    }

}

