<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market.proto

namespace Proto\Market;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.market.TickRequest</code>
 */
class TickRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.market.Stock stock = 1;</code>
     */
    protected $stock = null;
    /**
     * 格式：yyyy-mm-dd，不传的话默认最新一个交易日
     *
     * Generated from protobuf field <code>string date = 2;</code>
     */
    protected $date = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Market\Stock $stock
     *     @type string $date
     *           格式：yyyy-mm-dd，不传的话默认最新一个交易日
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Market::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.market.Stock stock = 1;</code>
     * @return \Proto\Market\Stock
     */
    public function getStock()
    {
        return $this->stock;
    }

    /**
     * Generated from protobuf field <code>.proto.market.Stock stock = 1;</code>
     * @param \Proto\Market\Stock $var
     * @return $this
     */
    public function setStock($var)
    {
        GPBUtil::checkMessage($var, \Proto\Market\Stock::class);
        $this->stock = $var;

        return $this;
    }

    /**
     * 格式：yyyy-mm-dd，不传的话默认最新一个交易日
     *
     * Generated from protobuf field <code>string date = 2;</code>
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * 格式：yyyy-mm-dd，不传的话默认最新一个交易日
     *
     * Generated from protobuf field <code>string date = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;

        return $this;
    }

}

